name: Terraform Configuration Aliases
description: Generate aliased provider blocks that satisfy required configuration aliases
branding:
  color: purple
  icon: code
inputs:
  path:
    description: The path to the Terraform module
    required: false
    default: './'
  terraform-config-inspect-version:
    description: The version of http://github.com/hashicorp/terraform-config-inspect to install
    required: false
    default: 81db043ad408976450c4af995dbe69ae70b26c82
outputs:
  providers:
    description: The generated provider configuration as a JSON string
    value: ${{ steps.aliases.outputs.providers }}
runs:
  using: composite
  steps:
    - run: |
        echo "::group::go install github.com/hashicorp/terraform-config-inspect"
        echo "version: $VERSION"

        cd "$(mktemp -d)"
        go mod init m

        go get github.com/hashicorp/terraform-config-inspect@$VERSION
        go install github.com/hashicorp/terraform-config-inspect

        echo "::endgroup::"
      shell: bash
      env:
        VERSION: ${{ inputs.terraform-config-inspect-version }}
    - run: echo "$(go env GOPATH)/bin" >> "$GITHUB_PATH"
      shell: bash
    - id: aliases
      run: |
        echo "Generating providers for configuration_aliases in Terraform module: ${{ inputs.path }}"
        ${{ github.action_path }}/providers.sh | tee aliased-providers.tf.json
        providers=$(jq -c < aliased-providers.tf.json)
        echo "::set-output name=providers::${providers}"
      shell: bash
      working-directory: ${{ inputs.path }}
