name: Terraform Configuration Aliases
description: Generate aliased provider blocks that satisfy required configuration aliases
branding:
  color: purple
  icon: code
inputs:
  path:
    description: The path to the Terraform module
    required: false
    default: './'
runs:
  using: composite
  steps:
    - name: Install terraform-config-inspect
      run: |
        echo "::group::go get github.com/hashicorp/terraform-config-inspect"
        go get github.com/hashicorp/terraform-config-inspect
        echo "::endgroup::"
      shell: bash
      env:
        GO111MODULE: 'on'
    - name: Add GOBIN to PATH
      run: echo "$(go env GOPATH)/bin" >> "$GITHUB_PATH"
      shell: bash
    - name: Generate aliased-providers.tf.json file
      run: |
        echo "Generating providers for configuration_aliases in Terraform module: ${{ inputs.path }}"
        ${{ github.action_path }}/providers.sh | tee aliased-providers.tf.json
      shell: bash
      working-directory: ${{ inputs.path }}
